# 服务器配置
[server]
port = 8484
mode = "debug"

# 数据库配置
[database]
host = "fn.vencenty.cn"
port = 53824
user = "root"
password = "UvbGrsVVaKDDzOEF"
dbname = "photo-kits"

# Minio 配置
[minio]
#endpoint = "s3.vencenty.cn"
#access_key = "IrBtP7ySGrQf82L22njM"
#secret_key = "gFUR5eWc47yRDXVNZqwcRVPtEc1veKOPPOXGhmxh"
#use_ssl = true
#bucket = "user-photos"
endpoint = "fn.vencenty.cn:29000"
access_key = "aalNu8yRU2vcGwgFQ0wk"
secret_key = "V4UQ7uWJdKQsJTwcpVht1aAK7PZK0yvDgdggdzAl"
use_ssl = false
bucket = "user-photos"
thumb_bucket = "img-thumbs"


[aliyun_minio]
endpoint = "storage.vagrancy.cn"
#endpoint = "127.0.0.1:29000"
access_key = "yLCkFYZzTJudMQAYgS3z"
secret_key = "gxr0Jvq0RORJLwvqZ3dWGjKELuL4NHrMvWElWana"
use_ssl = false
bucket = "user-photos"
thumb_bucket = "img-thumbs"
